/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:353142:
  appc.background(230);
} //_CODE_:window1:353142:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:693935:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:693935:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:792332:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:792332:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:775357:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
   vectors.add(new Vector2f(int(textfield1.getText()), int(textfield2.getText())));
   textfield1.setText("");
   textfield2.setText("");
} //_CODE_:button1:775357:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:textfield3:977619:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield3:977619:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:947754:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  sX=int(textfield3.getText());
  sY=int(textfield4.getText());
  float sHasil=0;
  for(Vector2f v : vectors){
    if(v.x==sX&&v.y==sY)
      sHasil =length(v);
  }
   textfield3.setText("");
   textfield4.setText("");
   if(sHasil==0)
     label3.setText("Vertex Tidak ditemukan");
    else
      label3.setText(Float.toString(sHasil));
} //_CODE_:button2:947754:

public void textfield4_change1(GTextField source, GEvent event) { //_CODE_:textfield4:847512:
  println("textfield4 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield4:847512:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Control", 0, 0, 220, 300, JAVA2D);
  window1.noLoop();
  window1.addDrawHandler(this, "win_draw1");
  textfield1 = new GTextField(window1, 15, 29, 52, 25, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  textfield2 = new GTextField(window1, 76, 29, 52, 24, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  button1 = new GButton(window1, 137, 26, 68, 26);
  button1.setText("Build Vector");
  button1.addEventHandler(this, "button1_click1");
  label1 = new GLabel(window1, 64, 3, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Build Vector");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 64, 69, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Lenght Vector");
  label2.setOpaque(false);
  textfield3 = new GTextField(window1, 14, 96, 53, 23, G4P.SCROLLBARS_NONE);
  textfield3.setOpaque(true);
  textfield3.addEventHandler(this, "textfield3_change1");
  button2 = new GButton(window1, 137, 96, 64, 24);
  button2.setText("Length");
  button2.addEventHandler(this, "button2_click1");
  textfield4 = new GTextField(window1, 74, 97, 55, 22, G4P.SCROLLBARS_NONE);
  textfield4.setOpaque(true);
  textfield4.addEventHandler(this, "textfield4_change1");
  label3 = new GLabel(window1, 14, 125, 184, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("--");
  label3.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GTextField textfield1; 
GTextField textfield2; 
GButton button1; 
GLabel label1; 
GLabel label2; 
GTextField textfield3; 
GButton button2; 
GTextField textfield4; 
GLabel label3; 